version: '3'
services:
  web:
    image:
       "abondar/todolist"
    ports:
      - 8024:8024
    # Link to containers in another service
    links:
      - db
    volumes:
      - $PWD
    networks:
          - todonet

  db:
    image: library/mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: alex21
      MYSQL_DATABASE: todo_list
    volumes:
          - ../../../../_local_mysql_data:/var/lib/mysql
    networks:
         - todonet


networks:
  todonet:
    driver: "bridge"
