

CREATE TABLE IF NOT EXISTS user(
  id BIGINT NOT NULL PRIMARY KEY  AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(512) NOT NULL

);

CREATE TABLE IF NOT EXISTS todo_list(
  id BIGINT NOT NULL PRIMARY KEY  AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  user_id BIGINT,
  CONSTRAINT  fk_user_list

  FOREIGN KEY(user_id) REFERENCES  user(id)
);

CREATE TABLE IF NOT EXISTS item(
  id BIGINT NOT NULL PRIMARY KEY  AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  done BOOL,
  list_id BIGINT,
  CONSTRAINT fk_list_item
  FOREIGN KEY (list_id) REFERENCES todo_list (id)
);
